name: media_picker_widget
description: A widget that picks media files from storage and allows you to place anywhere in the widget tree.
version: 0.0.9
homepage: https://github.com/rafid08/media_picker_widget

environment:
  sdk: ">=2.10.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  photo_manager:
    git:
      url: git@github.com:fastworkco/flutter_photo_manager.git
      ref: 97486ee114b62a13db4ee86f0baee796aee4718e

  sliding_up_panel: ^1.0.2
  # image_picker: ^0.6.7+22

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: